name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy main to Digital Ocean
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
            cd lugha/ && docker-compose down
            cd .. && rm -r lugha
            git clone git@github.com:khaldoun-xyz/lugha.git
            cp .env lugha/
            cd lugha/ && docker-compose up --build -d
            echo 'Deployment successful to digital ocean'
