name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy main to Digital Ocean
        uses: appleboy/ssh-action@v.0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
            mkdir deploy
            cd deploy
            git clone git@github.com:khaldoun-xyz/lugha.git
            docker-compose up --build -d
            echo 'Deployment successful to digital ocean'
